### ISSUE TITLE
Readme.md: usage examples

### ISSUE THREAD

**Issue by ddal** [gorhill/publicsuffixlist.js#12]
Hello!
  
    var domain = window.publicSuffixList.getDomain('something.uk');  
    // domain = ''  
should be...  

    var domain = window.publicSuffixList.getDomain('something.uk');
    // domain = 'something.uk'

**Comment by gorhill** [comment]
No, `something.uk` is not a valid domain, so getDomain() return an empty string.

**Comment by gorhill** [comment]
Wait, you are right, something change maybe, I remember `*.uk`...

**Comment by gorhill** [comment]
I changed `something.uk` to `police.uk`.

**Comment by ddal** [comment]
:+1:

**Comment by gorhill** [comment]
Just for my own sake, it did used to be `*.uk` a while ago: <https://github.com/gorhill/httpswitchboard/blob/4f42a597b1cd3efdc12168468dbdcdc6adc03893/assets/thirdparties/publicsuffix.org/list/effective_tld_names.dat>
