### ISSUE TITLE
Empty result for domain on "public suffix list"

### ISSUE THREAD

**Issue by Ede123** [gorhill/publicsuffixlist.js#13]
Rather a question than an issue (you might label accordingly):

* When a hostname is provided that is contained in "public suffix list", e.g. `suffixList.getDomain('police.uk');` as in the example in README.md, the result is an empty string (_""_).
* When a hostname is provided that is not contained in "public suffix list", e.g. `suffixList.getDomain('arbitrary.uk');`, the result is the input string (_"arbitrary.uk"_)

Isn't this kinda inconsistent? The actual domain for _"police.uk"_ should be _"police.uk"_ and not an empty string...
Is this by design to provide the additional information that the domain provided is actually part of the "public suffix list"  (and you leave it to the developer to figure out what an empty string means) or is there some other reason to do it this way?

**Comment by gorhill** [comment]
Everything which appears in the Public Suffix List ("PSL") is a domain suffix, not a domain. `police.uk` being a suffix, it can't be a valid domain, but `london.police.uk` is. `arbitrary.uk` is not in the PSL, but `uk` is. So `uk` is a suffix, and this means `arbitrary.uk` is a valid domain. `arbitrary.uk` would not be a valid domain if `arbitrary.uk` or `*.uk` was in the PSL.

The specification is [here](https://publicsuffix.org/list/).

**Comment by Ede123** [comment]
Thanks, so it's basically nomenclature:
* For me (as probably for the majority of people) `police.uk` is a valid domain name. It's a public suffix, too, but this does not make it an invalid domain per se.
* You seem to use the term "domain" slightly different: For you a domain is basically everything that is a subdomain of a public suffix (given that all TLDs are part of the PSL which tey seem to be from a quick glance) but not the public suffix itself.

One might also blame the somewhat suboptimal function name you chose (`getDomain()` in contrast to `checkPublicSuffix()` which is suggested in the specification's unit test).

You might think about adjusting your README.md accordingly to easily prevent such confusion in future...

**Comment by gorhill** [comment]
> One might also blame the somewhat suboptimal function name you chose

There is a `getPublicSuffix` method available. `getDomain` does what it suggests it does: it returns the domain for any hostname you pass it. `getDomain('blah.blah.blah.blah.police.uk')` will return `blah.police.uk`.

With your "for me `police.uk` is a valid domain name, you are bypassing the spec. I implemented it, which is the most important purpose for a reliable library.

**Comment by Ede123** [comment]
I didn't mean to second guess your implementation. Seems I rather misunderstood the specification and got myself confused by trying to visit `police.uk` as well as `githubusercontent.com` (both of which are public suffixes) which actually succeeded, but only because I got redirected to `www.police.uk` and `www.githubusercontent.com` respectively.
