### ISSUE TITLE
incorrect domain name being found

### ISSUE THREAD

**Issue by ryclair** [gorhill/publicsuffixlist.js#14]
This has been working well for me for most URLs. I could be something I'm doing wrong, but I'm finding that only "com" is being found as the domain name for the URLs below. Any thoughts?

http://www.baesystems.com/index.htm
http://www.thermofisher.com/en/about-us/life-technologies.html
http://www2.dupont.com/DuPont_Home/en_US/index.html

**Comment by gorhill** [comment]
You need to show exactly what method you are calling, with what parameter.

**Comment by ryclair** [comment]
Here is an example:
var website = "http://www.baesystems.com/index.htm";
var domain = window.publicSuffixList.getDomain(website);

**Comment by gorhill** [comment]
This is on the front page of the project:

    // Caller is responsible to pass in **hostnames** which are "canonicalized in the
    // normal way for hostnames": lower-case, punycode, and only a-z, 0-9, -, .

`http://www.baesystems.com/index.htm` is not a hostname, it's a URL.

**Comment by ryclair** [comment]
Ok, I misunderstood that then. Thanks for the update.
