### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by lumisota** [gorhill/publicsuffixlist.js#51]
Is there a preferred security contact address for this project?

**Comment by gorhill** [comment]
ubo-security@raymondhill.net

**Comment by gorhill** [comment]
Your message:

> Dear project maintainer/contributor,
> 
> We have identified that a GitHub project that you maintain, or are a main contributor to, contains an out-of-date version of the Public Suffix List (https://publicsuffix.org/). We are carrying out research to identify the potential impacts of using old versions of the Public Suffix List, and we intend to publish our results in academic conferences and journals. Our results will become publicly available in 21 days; this provides time to update your project with an up-to-date version of the Public Suffix List.
> 
> GitHub repository: gorhill/publicsuffixlist.js
> Public Suffix List path: docs/public_suffix_list.dat
> 
> GitHub repository: gorhill/uBO-Scope
> Public Suffix List path: assets/thirdparties/publicsuffix.org/list/public_suffix_list.dat
> 
> The Public Suffix List is regularly updated (generally a few times per week), and to ensure that the correct privacy boundaries are maintained between websites, applications that use it should routinely fetch an updated copy. If new suffixes are added to the list, and an old list is then used, privacy boundaries will not be constructed correctly, allowing for data (e.g., cookies) to be set incorrectly, potentially harming privacy.
> 
> There is further guidance on how the Public Suffix List should be used in ICANN’s “Advisory on the Use of Static TLD / Suffix Lists” at https://www.icann.org/en/system/files/files/sac-070-en.pdf.
> 
> If you have any questions about our research, or about usage of the Public Suffix List, please reply via e-mail to [sm@smcquistin.uk](mailto:sm@smcquistin.uk). 
> 
> Regards,
> 
> Stephen McQuistin

`docs/public_suffix_list.dat` is for test suite purpose only, it's not released as part of the source files. It looks like the issue here was filed as a result of automated search of `public_suffix_list.dat` regardless of the context in which it is used.

**Comment by gorhill** [comment]
Your message:

> Dear project maintainer/contributor,
> 
> We have identified that a GitHub project that you maintain, or are a main contributor to, contains an out-of-date version of the Public Suffix List (https://publicsuffix.org/). We are carrying out research to identify the potential impacts of using old versions of the Public Suffix List, and we intend to publish our results in academic conferences and journals. Our results will become publicly available in 21 days; this provides time to update your project with an up-to-date version of the Public Suffix List.
> 
> GitHub repository: gorhill/publicsuffixlist.js
> Public Suffix List path: docs/public_suffix_list.dat
> 
> GitHub repository: gorhill/uBO-Scope
> Public Suffix List path: assets/thirdparties/publicsuffix.org/list/public_suffix_list.dat
> 
> The Public Suffix List is regularly updated (generally a few times per week), and to ensure that the correct privacy boundaries are maintained between websites, applications that use it should routinely fetch an updated copy. If new suffixes are added to the list, and an old list is then used, privacy boundaries will not be constructed correctly, allowing for data (e.g., cookies) to be set incorrectly, potentially harming privacy.
> 
> There is further guidance on how the Public Suffix List should be used in ICANN’s “Advisory on the Use of Static TLD / Suffix Lists” at https://www.icann.org/en/system/files/files/sac-070-en.pdf.
> 
> If you have any questions about our research, or about usage of the Public Suffix List, please reply via e-mail to [xxxx]. 
> 
> Regards,
> 
> Stephen McQuistin

`docs/public_suffix_list.dat` is for test suite purpose only, it's not released as part of the source files. It looks like the issue here was filed as a result of automated search of `public_suffix_list.dat` regardless of the context in which it is used.

**Comment by lumisota** [comment]
Thank you for clarifying -- there was some effort to differentiate between use in production code vs. test suites (by manually looking at the code), but that's tricky without intimate knowledge of the code base.

**Comment by gorhill** [comment]
To be more concise (I missed that uBO-Scope was mentioned the first time):

> GitHub repository: gorhill/publicsuffixlist.js
> Public Suffix List path: docs/public_suffix_list.dat

`public_suffix_list.dat` is just used in a test suite to verify that the library works properly, it is not shipped as part of the library itself.

> GitHub repository: gorhill/uBO-Scope
> Public Suffix List path: assets/thirdparties/publicsuffix.org/list/public_suffix_list.dat

I just archived the project, it's not worked on anymore. It still is available out there, but the use of `public_suffix_list.dat` is only to find out whether a network request is 1st- or 3rd-party to the top-level frame. The extension is wholly passive, it does not act on data, and an out of date `public_suffix_list.dat` will at most cause it to potentially report incorrectly as to whether a network request is 1st- or 3rd-party.
